version: '2'
services:
    barservice-app:
        image: barservice
        external_links:
            - barservice-postgresql:postgresql
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_CLOUD_CONFIG_URI=http://admin:admin@registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/barService
            - JHIPSTER_SLEEP=10
    barservice-postgresql:
        container_name: barservice-postgresql
        image: postgres:9.5.4
        environment:
            - POSTGRES_USER=barService
            - POSTGRES_PASSWORD=
    
    fooservice-app:
        image: fooservice
        external_links:
            - fooservice-postgresql:postgresql
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_CLOUD_CONFIG_URI=http://admin:admin@registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/fooService
            - JHIPSTER_SLEEP=10
    fooservice-postgresql:
        container_name: fooservice-postgresql
        image: postgres:9.5.4
        environment:
            - POSTGRES_USER=fooService
            - POSTGRES_PASSWORD=
    
    gateway-app:
        image: gateway
        external_links:
            - gateway-postgresql:postgresql
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_CLOUD_CONFIG_URI=http://admin:admin@registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/gateway
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=cassandra
            - JHIPSTER_SLEEP=30
        ports:
            - 8080:8080
    gateway-postgresql:
        container_name: gateway-postgresql
        image: postgres:9.5.4
        environment:
            - POSTGRES_USER=gateway
            - POSTGRES_PASSWORD=
    
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry

    jhipster-elasticsearch:
        extends:
            file: jhipster-console.yml
            service: jhipster-elasticsearch
    jhipster-logstash:
        extends:
          file: jhipster-console.yml
          service: jhipster-logstash
    jhipster-console:
        extends:
            file: jhipster-console.yml
            service: jhipster-console
